# Generated by Django 3.2.9 on 2022-03-23 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.TextField()),
                ('company_name', models.TextField()),
                ('company_index', models.IntegerField()),
                ('non_payment_rate', models.FloatField()),
                ('complaints', models.FloatField()),
                ('payment_period', models.FloatField()),
                ('delay_period', models.FloatField()),
                ('delay_rate', models.FloatField()),
                ('capital_ratio', models.FloatField()),
                ('debt_ratio', models.FloatField()),
                ('net_asset', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_pk', models.IntegerField()),
                ('gis_cd', models.TextField()),
                ('ct_py_amt', models.IntegerField()),
                ('ct_py_cycle_cd', models.TextField()),
                ('ct_py_pd', models.IntegerField()),
                ('ct_chnl_cd', models.TextField()),
                ('insu_day', models.IntegerField()),
                ('insu_year', models.IntegerField()),
                ('mgg_grp', models.TextField()),
                ('mgg_cd', models.TextField()),
                ('mgg_cnt', models.IntegerField()),
                ('mgg_amt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DBOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_code', models.TextField()),
                ('option_name', models.TextField()),
                ('option_group_code', models.TextField()),
                ('option_group_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.TextField()),
                ('product_name', models.TextField()),
                ('product_link', models.TextField()),
                ('user_index', models.FloatField()),
                ('company_index', models.FloatField()),
                ('product_index', models.FloatField()),
                ('total_index', models.FloatField()),
                ('company_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype_code', models.TextField()),
                ('subtype_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.TextField()),
                ('bth_yr', models.IntegerField()),
                ('gender', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uc_pk', models.IntegerField()),
                ('contract_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.contract')),
                ('user_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_rate_pk', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('py', models.IntegerField()),
                ('gy', models.IntegerField()),
                ('sd', models.IntegerField()),
                ('mr', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_pk', models.IntegerField()),
                ('product_option', models.TextField()),
                ('coverage', models.IntegerField()),
                ('option_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.dboption')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_pk', models.IntegerField()),
                ('company_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.company')),
                ('contract_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.contract')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subtype_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.productsubtype'),
        ),
    ]
