# Generated by Django 3.2.9 on 2022-03-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subtype_code',
        ),
        migrations.RemoveField(
            model_name='productcontract',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='productcontract',
            name='contract_pk',
        ),
        migrations.RemoveField(
            model_name='productcontract',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='option_code',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='productrate',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='usercontract',
            name='contract_pk',
        ),
        migrations.RemoveField(
            model_name='usercontract',
            name='user_code',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='DBOption',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductContract',
        ),
        migrations.DeleteModel(
            name='ProductOption',
        ),
        migrations.DeleteModel(
            name='ProductRate',
        ),
        migrations.DeleteModel(
            name='ProductSubtype',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserContract',
        ),
    ]
