# Generated by Django 3.2.9 on 2022-03-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0002_auto_20220323_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_code', models.CharField(db_column='COMPANY_CODE', max_length=3, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, db_column='COMPANY_NAME', max_length=50, null=True)),
                ('company_index', models.FloatField(blank=True, db_column='COMPANY_INDEX', null=True)),
                ('non_payment_rate', models.FloatField(blank=True, db_column='NON_PAYMENT_RATE', null=True)),
                ('complaints', models.FloatField(blank=True, db_column='COMPLAINTS', null=True)),
                ('payment_period', models.FloatField(blank=True, db_column='PAYMENT_PERIOD', null=True)),
                ('delay_period', models.FloatField(blank=True, db_column='DELAY_PERIOD', null=True)),
                ('delay_rate', models.FloatField(blank=True, db_column='DELAY_RATE', null=True)),
                ('capital_ratio', models.FloatField(blank=True, db_column='CAPITAL_RATIO', null=True)),
                ('debt_ratio', models.TextField(blank=True, db_column='DEBT_RATIO', null=True)),
                ('net_asset', models.TextField(blank=True, db_column='NET_ASSET', null=True)),
            ],
            options={
                'db_table': 'COMPANY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_pk', models.IntegerField(db_column='CONTRACT_PK', primary_key=True, serialize=False)),
                ('gis_cd', models.CharField(blank=True, db_column='GIS_CD', max_length=10, null=True)),
                ('ct_py_amt', models.IntegerField(blank=True, db_column='CT_PY_AMT', null=True)),
                ('ct_py_pd', models.IntegerField(blank=True, db_column='CT_PY_PD', null=True)),
                ('ct_chnl_cd', models.CharField(blank=True, db_column='CT_CHNL_CD', max_length=10, null=True)),
                ('insu_day', models.IntegerField(blank=True, db_column='INSU_DAY', null=True)),
                ('insu_year', models.IntegerField(blank=True, db_column='INSU_YEAR', null=True)),
                ('mgg_grp', models.CharField(blank=True, db_column='MGG_GRP', max_length=10, null=True)),
            ],
            options={
                'db_table': 'CONTRACT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbOption',
            fields=[
                ('option_code', models.CharField(db_column='OPTION_CODE', max_length=5, primary_key=True, serialize=False)),
                ('option_name', models.CharField(blank=True, db_column='OPTION_NAME', max_length=255, null=True)),
                ('option_group_code', models.CharField(blank=True, db_column='OPTION_GROUP_CODE', max_length=5, null=True)),
                ('option_group_name', models.CharField(blank=True, db_column='OPTION_GROUP_NAME', max_length=255, null=True)),
            ],
            options={
                'db_table': 'DB_OPTION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_code', models.CharField(db_column='PRODUCT_CODE', max_length=6, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, db_column='PRODUCT_NAME', max_length=255, null=True)),
                ('product_link', models.CharField(blank=True, db_column='PRODUCT_LINK', max_length=255, null=True)),
                ('user_index', models.TextField(blank=True, db_column='USER_INDEX', null=True)),
                ('company_index', models.TextField(blank=True, db_column='COMPANY_INDEX', null=True)),
                ('product_index', models.TextField(blank=True, db_column='PRODUCT_INDEX', null=True)),
                ('total_index', models.TextField(blank=True, db_column='TOTAL_INDEX', null=True)),
            ],
            options={
                'db_table': 'PRODUCT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('option_pk', models.IntegerField(db_column='OPTION_PK', primary_key=True, serialize=False)),
                ('product_option', models.TextField(blank=True, db_column='PRODUCT_OPTION', null=True)),
                ('coverage', models.IntegerField(blank=True, db_column='COVERAGE', null=True)),
            ],
            options={
                'db_table': 'PRODUCT_OPTION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRate',
            fields=[
                ('product_rate_pk', models.IntegerField(db_column='PRODUCT_RATE_PK', primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, db_column='AGE', null=True)),
                ('gender', models.CharField(blank=True, db_column='GENDER', max_length=10, null=True)),
                ('rate', models.IntegerField(blank=True, db_column='RATE', null=True)),
                ('py', models.IntegerField(blank=True, db_column='PY', null=True)),
                ('gy', models.IntegerField(blank=True, db_column='GY', null=True)),
                ('sd', models.IntegerField(blank=True, db_column='SD', null=True)),
                ('mr', models.IntegerField(blank=True, db_column='MR', null=True)),
            ],
            options={
                'db_table': 'PRODUCT_RATE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSubtype',
            fields=[
                ('subtype_code', models.CharField(db_column='SUBTYPE_CODE', max_length=10, primary_key=True, serialize=False)),
                ('subtype_name', models.CharField(blank=True, db_column='SUBTYPE_NAME', max_length=10, null=True)),
            ],
            options={
                'db_table': 'PRODUCT_SUBTYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchCompany',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_code', models.TextField()),
                ('company_name', models.TextField()),
                ('company_index', models.IntegerField()),
                ('non_payment_rate', models.FloatField()),
                ('complaints', models.FloatField()),
                ('payment_period', models.FloatField()),
                ('delay_period', models.FloatField()),
                ('delay_rate', models.FloatField()),
                ('capital_ratio', models.FloatField()),
                ('debt_ratio', models.FloatField()),
                ('net_asset', models.FloatField()),
            ],
            options={
                'db_table': 'search_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchContract',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contract_pk', models.IntegerField()),
                ('gis_cd', models.TextField()),
                ('ct_py_amt', models.IntegerField()),
                ('ct_py_cycle_cd', models.TextField()),
                ('ct_py_pd', models.IntegerField()),
                ('ct_chnl_cd', models.TextField()),
                ('insu_day', models.IntegerField()),
                ('insu_year', models.IntegerField()),
                ('mgg_grp', models.TextField()),
                ('mgg_cd', models.TextField()),
                ('mgg_cnt', models.IntegerField()),
                ('mgg_amt', models.IntegerField()),
            ],
            options={
                'db_table': 'search_contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchDboption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option_code', models.TextField()),
                ('option_name', models.TextField()),
                ('option_group_code', models.TextField()),
                ('option_group_name', models.TextField()),
            ],
            options={
                'db_table': 'search_dboption',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_code', models.TextField()),
                ('product_name', models.TextField()),
                ('product_link', models.TextField()),
                ('user_index', models.FloatField()),
                ('company_index', models.FloatField()),
                ('product_index', models.FloatField()),
                ('total_index', models.FloatField()),
            ],
            options={
                'db_table': 'search_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchProductcontract',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pc_pk', models.IntegerField()),
            ],
            options={
                'db_table': 'search_productcontract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchProductoption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option_pk', models.IntegerField()),
                ('product_option', models.TextField()),
                ('coverage', models.IntegerField()),
            ],
            options={
                'db_table': 'search_productoption',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchProductrate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_rate_pk', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('py', models.IntegerField()),
                ('gy', models.IntegerField()),
                ('sd', models.IntegerField()),
                ('mr', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'search_productrate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchProductsubtype',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subtype_code', models.TextField()),
                ('subtype_name', models.TextField()),
            ],
            options={
                'db_table': 'search_productsubtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_code', models.TextField()),
                ('bth_yr', models.IntegerField()),
                ('gender', models.TextField()),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'search_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchUsercontract',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uc_pk', models.IntegerField()),
            ],
            options={
                'db_table': 'search_usercontract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_code', models.CharField(db_column='USER_CODE', max_length=10, primary_key=True, serialize=False)),
                ('bth_yr', models.IntegerField(blank=True, db_column='BTH_YR', null=True)),
                ('gender', models.CharField(blank=True, db_column='GENDER', max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, db_column='AGE', null=True)),
            ],
            options={
                'db_table': 'USER',
                'managed': False,
            },
        ),
    ]
