# Generated by Django 4.0.3 on 2022-03-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_compan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='DbOption',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductOption',
        ),
        migrations.DeleteModel(
            name='ProductRate',
        ),
        migrations.DeleteModel(
            name='ProductSubtype',
        ),
        migrations.DeleteModel(
            name='SearchCompany',
        ),
        migrations.DeleteModel(
            name='SearchContract',
        ),
        migrations.DeleteModel(
            name='SearchDboption',
        ),
        migrations.DeleteModel(
            name='SearchProduct',
        ),
        migrations.DeleteModel(
            name='SearchProductcontract',
        ),
        migrations.DeleteModel(
            name='SearchProductoption',
        ),
        migrations.DeleteModel(
            name='SearchProductrate',
        ),
        migrations.DeleteModel(
            name='SearchProductsubtype',
        ),
        migrations.DeleteModel(
            name='SearchUser',
        ),
        migrations.DeleteModel(
            name='SearchUsercontract',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
